  version: '3.3'

  services:
    ubuntu:
      image: ubuntu:22.04
      container_name: ubuntu-ansible
      ports:
        - "2222:22"
        - "8080:80"
      command: >
        bash -c "
          apt update &&
          apt install -y openssh-server sudo &&
          useradd -m ansible &&
          echo 'ansible:ansible' | chpasswd &&
          echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
          mkdir -p /run/sshd &&
          /usr/sbin/sshd -D
        "
      networks:
        - ansible-net
      privileged: true

    rocky:
      image: rockylinux:9
      container_name: rocky-ansible
      ports:
        - "2223:22"
        - "8081:80"
      command: >
        bash -c "
          dnf install -y openssh-server sudo passwd &&
          useradd -m ansible &&
          echo 'ansible:ansible' | chpasswd &&
          echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
          ssh-keygen -A &&
          mkdir -p /run/sshd &&
          /usr/sbin/sshd -D
        "
      networks:
        - ansible-net
      privileged: true

  networks:
    ansible-net:
      driver: bridge
