- name: Deploy virtualhost configuration
  template:
    src: wordpress.conf.j2
    dest: "{{ wordpress_vhost_conf }}"
  notify: Reload Apache

- name: Enable site and mod_rewrite (Debian)
  block:
    - name: Enable site
      command: a2ensite wordpress.conf
      args:
        creates: /etc/apache2/sites-enabled/wordpress.conf
    - name: Enable mod_rewrite
      command: a2enmod rewrite
    - name: Reload Apache
      service:
        name: apache2
        state: reloaded
  when: ansible_os_family == "Debian"

- name: Set ServerName to localhost (Rocky)
  copy:
    dest: /etc/httpd/conf.d/servername.conf
    content: "ServerName localhost\n"
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat"
